name: LookML Validation Pipeline

on:
  pull_request:
    branches: [ main, master, develop ]
    paths: 
      - '**/*.lookml'
      - '**/*.lkml'
      - '**/*.model'
      - '**/*.view'
      - '**/*.explore'
      - '**/*.dashboard'
      - 'manifest.lkml'
  push:
    branches: [ main, master ]
    paths: 
      - '**/*.lookml'
      - '**/*.lkml'
      - '**/*.model'
      - '**/*.view'
      - '**/*.explore'
      - '**/*.dashboard'
      - 'manifest.lkml'

jobs:
  lookml-validation:
    runs-on: ubuntu-latest
    name: Validate LookML Code
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/.github/scripts/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt
    
    - name: Setup Looker configuration
      run: |
        cp .github/config/looker-config.ini.template looker.ini
        sed -i "s|YOUR_CLIENT_ID|${{ secrets.LOOKER_CLIENT_ID }}|g" looker.ini
        sed -i "s|YOUR_CLIENT_SECRET|${{ secrets.LOOKER_CLIENT_SECRET }}|g" looker.ini
        sed -i "s|YOUR_LOOKER_BASE_URL|${{ secrets.LOOKER_BASE_URL }}|g" looker.ini
      env:
        LOOKER_CLIENT_ID: ${{ secrets.LOOKER_CLIENT_ID }}
        LOOKER_CLIENT_SECRET: ${{ secrets.LOOKER_CLIENT_SECRET }}
        LOOKER_BASE_URL: ${{ secrets.LOOKER_BASE_URL }}
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.lookml
          **/*.lkml
          **/*.model
          **/*.view
          **/*.explore
          **/*.dashboard
          manifest.lkml
    
    - name: Display changed LookML files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Changed LookML files:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
    
    # Step 1: LookML Syntax Validation
    - name: Validate LookML Syntax
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Running LookML syntax validation..."
        python .github/scripts/looker-validator.py --project-name="bi_sandbox"
      continue-on-error: false
    
    # Step 2: Custom LookML Linting
    - name: Run LookML Linting
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Running custom LookML linting..."
        python .github/scripts/lookml-linter.py --files="${{ steps.changed-files.outputs.all_changed_files }}"
      continue-on-error: false
    
    # Step 3: LookML Data Tests
    - name: Run LookML Data Tests
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Running LookML data tests..."
        python .github/scripts/lookml-data-tests.py --project-name="bi_sandbox"
      continue-on-error: true
    
    # Step 4: Content Validation (BI Sandbox folder)
    - name: Run Content Validation
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Running content validation for BI Sandbox folder..."
        python .github/scripts/lookml-content-validator.py --folder-name="BI Sandbox"
      continue-on-error: true  # Allow pipeline to continue even if content has errors
    
    # Step 5: Generate Validation Report
    - name: Generate Validation Report
      if: always() && steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Generating validation report..."
        python .github/scripts/report-generator.py
    
    # Step 6: Upload validation artifacts
    - name: Upload validation artifacts
      if: always() && steps.changed-files.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: lookml-validation-results
        path: |
          validation_results.json
          linting_results.json
          data_tests_results.json
          content_validation_results.json
          validation_summary.md
        retention-days: 30
    
    # Step 7: Check validation results
    - name: Check validation results
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        python .github/scripts/check-results.py
    
    # Step 8: Comment PR with results
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          if (!fs.existsSync('pr_comment.md')) {
            console.log('No PR comment file found');
            return;
          }
          
          const comment = fs.readFileSync('pr_comment.md', 'utf8');
          
          // Check for existing comments from this workflow
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          // Look for existing LookML validation comment
          const botComment = comments.find(comment => 
            comment.user.login === 'github-actions[bot]' && 
            comment.body.includes('LookML Validation Results')
          );
          
          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
            console.log('Updated existing PR comment');
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            console.log('Created new PR comment');
          }
